version: '3'
services:
  vueApp:
    build:                          # 这里指的是我们刚刚撸的 Dockerfile 文件
      context: .                    
      dockerfile: Dockerfile
    image: nodejs                   # 镜像名称
    container_name: vue_app          # 容器名称
    restart: always                 # 重启方式

  # mobile-web-best-practice: #项目的service name
  #   container_name: 'docker-vue-app' #容器名称
  #   image: nginx #指定镜像
  #   restart: always
  #   ports:
  #     - 81:80
  #   volumes:
  #     #~ ./nginx.conf为宿主机目录, /etc/nginx为容器目录
  #     - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
  #     #~ ./dist 为宿主机 build 后的dist目录, /usr/src/app为容器目录,
  #     - ./dist:/usr/share/nginx/html/ #挂载项目
  #   links:                          # 容器连接
  #     - vue_app:vue_app
  #   privileged: true

